### ISSUE TITLE
Alternate of ZegoInRoomLiveCommentingViewItem

### ISSUE THREAD

**Issue by AwaisQazii** [ZEGOCLOUD/zego_uikit_prebuilt_live_streaming_flutter#10]
ZegoInRoomLiveCommentingViewItem is not defined in newer version

 if (message.user.id == model.userId.value) {
          return ZegoInRoomLiveCommentingViewItem(
            user: message.user,
            message: message.message,
          );

**Comment by AwaisQazii** [comment]
The method 'ZegoInRoomLiveCommentingViewItem' isn't defined for the type 'LiveStreamView'

**Comment by yoer** [comment]
what's your previous version?

**Comment by yoer** [comment]
In version 2.13.0, it has been renamed to `ZegoInRoomMessageViewItem`.

**Comment by AwaisQazii** [comment]
Thank you
