### ISSUE TITLE
Usage with Flutter web

### ISSUE THREAD

**Issue by anushka-mim** [ZEGOCLOUD/zego_uikit_prebuilt_live_streaming_flutter#16]
- [x] I have read the [Getting Started](https://docs.zegocloud.com/article/14846) and [Getting Started with coHost](https://docs.zegocloud.com/article/14882) 

- [x] I have already searched for the same problem

## Environment

| Technology            | Version       |
|-----------------------| ------------- |
| Flutter version       |      3.22.3         |
| Plugin version        |         ^3.13.5      |
| Android version       |               |
| iOS version           |               |
| macOS version         |               |
| Xcode version         |               |
| Google Chrome version |        131.0.6778.70       |

Device information: 

## Description

**Expected behavior:** 
There is no mention in the documentation that this package cannot be used on Flutter web so I expected it to work.

**Current behavior:** 
A platform exception is thrown when trying to start streaming.

## Steps to reproduce

```
ZegoUIKitPrebuiltLiveStreaming(
          appID: appEnvironment.zegoAppId,
          userID: userId,
          userName: userName,
          liveID: roomId,
          token: token,
          config: (isHost ? hostConfig : audienceConfig)
)
```

## Images   
<img src="https://github.com/user-attachments/assets/b6d7b390-ad75-4e39-94e1-cfdb350b7a7a" width="300" />

## Stacktrace/Logcat 
```

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following UnsupportedError was thrown building ZegoLiveStreamingPage(dirty, state:
_ZegoUIKitPrebuiltLiveStreamingState#a22d9):
Unsupported operation: Platform._operatingSystem

The relevant error-causing widget was:
  ZegoUIKitPrebuiltLiveStreaming
  ZegoUIKitPrebuiltLiveStreaming:file:///C:/Users/anushka/Documents/work/fanclub/fan-club-app/lib/ui/page/video/broadcast/broadcast_live_page.dart:72:14

When the exception was thrown, this was the stack:
../dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3            throw_
../dart-sdk/lib/_internal/js_dev_runtime/patch/io_patch.dart 244:5                        _operatingSystem
../dart-sdk/lib/io/platform_impl.dart 56:40                                               get operatingSystem
../dart-sdk/lib/io/platform.dart 83:44                                                    get operatingSystem
../dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 1071:8       get
../dart-sdk/lib/io/platform.dart 156:50                                                   get isAndroid
../dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 1071:8       get
../packages/zego_uikit_prebuilt_live_streaming/src/components/live_streaming.dart 427:18  build
```

**Comment by yoer** [comment]
not support web
