### ISSUE TITLE
The camera view is leftRight

### ISSUE THREAD

**Issue by MianAzhar** [ZEGOCLOUD/zego_uikit_prebuilt_live_streaming_flutter#2]
live streaming show image left right
face looks fine but the text is does look right
![1672909778895](https://user-images.githubusercontent.com/11595873/210743106-29e79397-8606-45ad-9b62-1596ee23a273.JPEG)

**Comment by yoer** [comment]
we will fix this problem, or provide a setting in config
thanks for your advice

**Comment by yoer** [comment]
The latest version supports it now
```dart
..config.audioVideoViewConfig.isVideoMirror = false
```
