### ISSUE TITLE
AVerTP protocol does not work with my network

### ISSUE THREAD

**Issue by HoussemBousmaha** [ZEGOCLOUD/zego_uikit_prebuilt_live_streaming_flutter#4]
I am trying to publish a live stream using the zego express engine package.

calling the method ZegoExpressEngine.instance.startPublishingStream(streamId) does not throw any error.

it starts the publishing but it cannot quite start publishing, so it tries to restart publishing and just keep restarting and restarting and not actually publishing the live video, audio stream!

i found a solution which is using a vpn network. it worked fine and well! but the latency it toooooo high because vpn server is far away from me.

are there any solutions?

**Comment by yoer** [comment]
[zego-express-flutter-sdk](https://github.com/zegoim/zego-express-flutter-sdk)

**Comment by yoer** [comment]
@HoussemBousmaha you should report this issue on [zego-express-flutter-sdk](https://github.com/zegoim/zego-express-flutter-sdk)
