### ISSUE TITLE
flutter screenutil

### ISSUE THREAD

**Issue by MozafarAlali93** [ZEGOCLOUD/zego_uikit_prebuilt_live_streaming_flutter#6]
There is a problem if you use flutter_screenutil in your application. When you use this package, all dimensions in the application become incorrect.

**Comment by yoer** [comment]
you can set your appDesignSize in ZegoUIKitPrebuiltLiveStreaming

**Comment by Aliabbas-creator** [comment]
use methods of screenutils().setwidth(10)

**Comment by MozafarAlali93** [comment]
> you can set your appDesignSize in ZegoUIKitPrebuiltLiveStreaming

I tried this method. but it didn't work and LiveStreaming page Design incorrect

**Comment by MozafarAlali93** [comment]
> 

Where is this code added?

**Comment by MozafarAlali93** [comment]
> use methods of screenutils().setwidth(10)

Where should I add this code?

**Comment by yoer** [comment]
This has been fixed in the latest version

**Comment by yoer** [comment]
. please update the newest sdk version: 2.4.1
2. we have brought "flutter_screenutil_zego" and don't depend on the old "flutter_screenutil" library. Avoided the UI resizing issue caused by the memory sharing of the flutter_screenutil single instance's design size from the root.
